---
- name: Ensure Python dependencies are installed
  ansible.builtin.apt:
    pkg:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libsqlite3-dev
      - libreadline-dev
      - libffi-dev
      - libbz2-dev
    state: present
    update_cache: true

- name: Ensure Python source code is present
  ansible.builtin.get_url:
    url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: /tmp
    mode: '0644'

- name: Ensure Python source code is unarchived
  ansible.builtin.unarchive:
    src: "/tmp/Python-{{ python_version }}.tgz"
    dest: /tmp
    remote_src: true

- name: Ensure Python installer is properly configured
  ansible.builtin.command:
    cmd: ./configure --enable-optimizations --with-ensurepip=install
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/tmp/Python-{{ python_version }}/Makefile"

- name: Ensure Python is compiled
  ansible.builtin.command:
    cmd: make -j8
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/tmp/Python-{{ python_version }}/python"

- name: Ensure Python is installed
  ansible.builtin.command:
    cmd: make install
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/usr/local/bin/python{{ python_version.split('.')[:-1] | join('.') }}"
