source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'bcrypt_pbkdf', '~> 1.1'
gem 'capistrano', '~> 3.18.0'
gem 'capistrano-yarn', '~> 2.0', '>= 2.0.2'
gem 'ed25519', '~> 1.3'
gem 'net-ssh', '~> 7.2.1'