on:
  # Triggers the workflow on push or pull request events but only for the develop branch.
  push:
    branches:
      - develop
  # Trigger the workflow also when you put the PR ready for review.
  pull_request:
    types: ready_for_review
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:
name: TestSuite
jobs:
  iOS:
    name: Tests
    runs-on: macos-13
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=17.0.1,name=iPhone 15']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout LFS files
        uses: nschloe/action-checkout-with-lfs-cache@v1

      - uses: actions/cache@v4
        id: cocoapods-cache
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - uses: actions/cache@v4
        id: spm-cache
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Build
        run: |
          pod install
          mv SharedApp/Secrets.swift.example SharedApp/Secrets.swift
          echo "let secretDriverTesterEmail = \"${{ secrets.DRIVER_TESTER_EMAIL }}\"" >> SharedApp/Secrets.swift
          echo "let secretDriverTesterPassword = \"${{ secrets.DRIVER_TESTER_PWD }}\"" >> SharedApp/Secrets.swift
          sudo xcode-select -s /Applications/Xcode_15.0.app/Contents/Developer; xcodebuild -version
          xcodebuild build test -workspace ./FreeRide.xcworkspace -scheme RiderApp-Stage -destination "${destination}" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
          xcodebuild build test -workspace ./FreeRide.xcworkspace -scheme DriverApp-Stage -destination "${destination}" CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
    env:
      destination: ${{ matrix.destination }}
