---

- name: Installing dependencies
  apt:
    pkg: apt-transport-https
    state: present

- name: Adding APT key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: Add APT repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main"
    update_cache: yes

- name: Installing packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - "{{ nodejs_package }}"
    - build-essential
